[2023-03-21 03:42:47,317] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:37:45.523481+00:00 [queued]>
[2023-03-21 03:42:47,326] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:37:45.523481+00:00 [queued]>
[2023-03-21 03:42:47,326] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:42:47,327] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-03-21 03:42:47,327] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:42:47,340] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): download_price> on 2023-03-21 03:37:45.523481+00:00
[2023-03-21 03:42:47,345] {standard_task_runner.py:52} INFO - Started process 1423 to run task
[2023-03-21 03:42:47,349] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_stock', 'download_price', 'scheduled__2023-03-21T03:37:45.523481+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/download_stock_price.py', '--cfg-path', '/tmp/tmpg6yj4w8j', '--error-file', '/tmp/tmpj_z46j8s']
[2023-03-21 03:42:47,351] {standard_task_runner.py:80} INFO - Job 100: Subtask download_price
[2023-03-21 03:42:47,422] {task_command.py:371} INFO - Running <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:37:45.523481+00:00 [running]> on host 6b2dd5cdd356
[2023-03-21 03:42:47,494] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_stock
AIRFLOW_CTX_TASK_ID=download_price
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T03:37:45.523481+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T03:37:45.523481+00:00
[2023-03-21 03:42:48,145] {logging_mixin.py:115} INFO - <class 'pandas.core.frame.DataFrame'>
[2023-03-21 03:42:48,146] {logging_mixin.py:115} INFO - (9330, 7)
[2023-03-21 03:42:48,147] {logging_mixin.py:115} INFO - /opt/***
[2023-03-21 03:42:48,148] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_stock_price.py", line 46, in download_price
    with open(f'/Users/chris_lo/PycharmProjects/airflow/logs/{ticker}.csv','w') as writer:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chris_lo/PycharmProjects/airflow/logs/MSFT.csv'
[2023-03-21 03:42:48,158] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=download_stock, task_id=download_price, execution_date=20230321T033745, start_date=20230321T034247, end_date=20230321T034248
[2023-03-21 03:42:48,169] {standard_task_runner.py:97} ERROR - Failed to execute job 100 for task download_price ([Errno 2] No such file or directory: '/Users/chris_lo/PycharmProjects/airflow/logs/MSFT.csv'; 1423)
[2023-03-21 03:42:48,221] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-21 03:42:48,256] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
