[2023-03-21 03:38:30,219] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_stock.download_price manual__2023-03-21T03:38:28.418487+00:00 [queued]>
[2023-03-21 03:38:30,230] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_stock.download_price manual__2023-03-21T03:38:28.418487+00:00 [queued]>
[2023-03-21 03:38:30,231] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:38:30,232] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-03-21 03:38:30,232] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:38:30,250] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): download_price> on 2023-03-21 03:38:28.418487+00:00
[2023-03-21 03:38:30,257] {standard_task_runner.py:52} INFO - Started process 1342 to run task
[2023-03-21 03:38:30,262] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_stock', 'download_price', 'manual__2023-03-21T03:38:28.418487+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/download_stock_price.py', '--cfg-path', '/tmp/tmpbryftsug', '--error-file', '/tmp/tmp7wt34q4z']
[2023-03-21 03:38:30,265] {standard_task_runner.py:80} INFO - Job 97: Subtask download_price
[2023-03-21 03:38:30,351] {task_command.py:371} INFO - Running <TaskInstance: download_stock.download_price manual__2023-03-21T03:38:28.418487+00:00 [running]> on host 6b2dd5cdd356
[2023-03-21 03:38:30,433] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_stock
AIRFLOW_CTX_TASK_ID=download_price
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T03:38:28.418487+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-21T03:38:28.418487+00:00
[2023-03-21 03:38:31,068] {logging_mixin.py:115} INFO - <class 'pandas.core.frame.DataFrame'>
[2023-03-21 03:38:31,069] {logging_mixin.py:115} INFO - (9330, 7)
[2023-03-21 03:38:31,070] {logging_mixin.py:115} INFO - /opt/***
[2023-03-21 03:38:31,070] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_stock_price.py", line 47, in download_price
    with open(f'/Users/chris_lo/PycharmProjects/airflow/logs/{ticker}.csv','w') as writer:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chris_lo/PycharmProjects/airflow/logs/MSFT.csv'
[2023-03-21 03:38:31,082] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=download_stock, task_id=download_price, execution_date=20230321T033828, start_date=20230321T033830, end_date=20230321T033831
[2023-03-21 03:38:31,092] {standard_task_runner.py:97} ERROR - Failed to execute job 97 for task download_price ([Errno 2] No such file or directory: '/Users/chris_lo/PycharmProjects/airflow/logs/MSFT.csv'; 1342)
[2023-03-21 03:38:31,121] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-21 03:38:31,152] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
