[2023-03-21 03:42:43,939] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:32:40.470172+00:00 [queued]>
[2023-03-21 03:42:43,947] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:32:40.470172+00:00 [queued]>
[2023-03-21 03:42:43,947] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:42:43,948] {taskinstance.py:1377} INFO - Starting attempt 2 of 2
[2023-03-21 03:42:43,948] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:42:43,960] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): download_price> on 2023-03-21 03:32:40.470172+00:00
[2023-03-21 03:42:43,965] {standard_task_runner.py:52} INFO - Started process 1420 to run task
[2023-03-21 03:42:43,968] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_stock', 'download_price', 'scheduled__2023-03-21T03:32:40.470172+00:00', '--job-id', '99', '--raw', '--subdir', 'DAGS_FOLDER/download_stock_price.py', '--cfg-path', '/tmp/tmpm_9bir0r', '--error-file', '/tmp/tmpdz9hj5lp']
[2023-03-21 03:42:43,971] {standard_task_runner.py:80} INFO - Job 99: Subtask download_price
[2023-03-21 03:42:44,041] {task_command.py:371} INFO - Running <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:32:40.470172+00:00 [running]> on host 6b2dd5cdd356
[2023-03-21 03:42:44,118] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_stock
AIRFLOW_CTX_TASK_ID=download_price
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T03:32:40.470172+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T03:32:40.470172+00:00
[2023-03-21 03:42:44,727] {logging_mixin.py:115} INFO - <class 'pandas.core.frame.DataFrame'>
[2023-03-21 03:42:44,728] {logging_mixin.py:115} INFO - (9330, 7)
[2023-03-21 03:42:44,729] {logging_mixin.py:115} INFO - /opt/***
[2023-03-21 03:42:44,729] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_stock_price.py", line 46, in download_price
    with open(f'/Users/chris_lo/PycharmProjects/airflow/logs/{ticker}.csv','w') as writer:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chris_lo/PycharmProjects/airflow/logs/MSFT.csv'
[2023-03-21 03:42:44,739] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=download_stock, task_id=download_price, execution_date=20230321T033240, start_date=20230321T034243, end_date=20230321T034244
[2023-03-21 03:42:44,752] {standard_task_runner.py:97} ERROR - Failed to execute job 99 for task download_price ([Errno 2] No such file or directory: '/Users/chris_lo/PycharmProjects/airflow/logs/MSFT.csv'; 1420)
[2023-03-21 03:42:44,791] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-21 03:42:44,824] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
