[2023-03-21 03:47:52,196] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:42:50.463173+00:00 [queued]>
[2023-03-21 03:47:52,206] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:42:50.463173+00:00 [queued]>
[2023-03-21 03:47:52,207] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:47:52,208] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2023-03-21 03:47:52,208] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2023-03-21 03:47:52,353] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): download_price> on 2023-03-21 03:42:50.463173+00:00
[2023-03-21 03:47:52,360] {standard_task_runner.py:52} INFO - Started process 142 to run task
[2023-03-21 03:47:52,365] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'download_stock', 'download_price', 'scheduled__2023-03-21T03:42:50.463173+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/download_stock_price.py', '--cfg-path', '/tmp/tmpt_dqjd1y', '--error-file', '/tmp/tmpoeqz711k']
[2023-03-21 03:47:52,368] {standard_task_runner.py:80} INFO - Job 137: Subtask download_price
[2023-03-21 03:47:52,444] {task_command.py:371} INFO - Running <TaskInstance: download_stock.download_price scheduled__2023-03-21T03:42:50.463173+00:00 [running]> on host 6b2dd5cdd356
[2023-03-21 03:47:52,516] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_stock
AIRFLOW_CTX_TASK_ID=download_price
AIRFLOW_CTX_EXECUTION_DATE=2023-03-21T03:42:50.463173+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-21T03:42:50.463173+00:00
[2023-03-21 03:47:52,934] {logging_mixin.py:115} INFO - <class 'pandas.core.frame.DataFrame'>
[2023-03-21 03:47:52,935] {logging_mixin.py:115} INFO - (9330, 7)
[2023-03-21 03:47:52,936] {logging_mixin.py:115} INFO - /opt/***
[2023-03-21 03:47:52,937] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/download_stock_price.py", line 46, in download_price
    with open(f'/Users/chris_lo/PycharmProjects/airflow/logs/{ticker}.csv','w') as writer:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/chris_lo/PycharmProjects/airflow/logs/MSFT.csv'
[2023-03-21 03:47:52,945] {taskinstance.py:1420} INFO - Marking task as UP_FOR_RETRY. dag_id=download_stock, task_id=download_price, execution_date=20230321T034250, start_date=20230321T034752, end_date=20230321T034752
[2023-03-21 03:47:52,954] {standard_task_runner.py:97} ERROR - Failed to execute job 137 for task download_price ([Errno 2] No such file or directory: '/Users/chris_lo/PycharmProjects/airflow/logs/MSFT.csv'; 142)
[2023-03-21 03:47:52,982] {local_task_job.py:156} INFO - Task exited with return code 1
[2023-03-21 03:47:53,014] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
