[2023-03-22T07:48:25.602+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sql_dags.write_to_mysql manual__2023-03-22T07:48:23.873072+00:00 [queued]>
[2023-03-22T07:48:25.613+0000] {taskinstance.py:1084} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sql_dags.write_to_mysql manual__2023-03-22T07:48:23.873072+00:00 [queued]>
[2023-03-22T07:48:25.614+0000] {taskinstance.py:1282} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:48:25.615+0000] {taskinstance.py:1283} INFO - Starting attempt 1 of 2
[2023-03-22T07:48:25.615+0000] {taskinstance.py:1284} INFO - 
--------------------------------------------------------------------------------
[2023-03-22T07:48:25.633+0000] {taskinstance.py:1303} INFO - Executing <Task(PythonOperator): write_to_mysql> on 2023-03-22 07:48:23.873072+00:00
[2023-03-22T07:48:25.640+0000] {standard_task_runner.py:55} INFO - Started process 1096 to run task
[2023-03-22T07:48:25.646+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'sql_dags', 'write_to_mysql', 'manual__2023-03-22T07:48:23.873072+00:00', '--job-id', '403', '--raw', '--subdir', 'DAGS_FOLDER/sql_dags.py', '--cfg-path', '/tmp/tmpa9gyuk9y']
[2023-03-22T07:48:25.647+0000] {standard_task_runner.py:83} INFO - Job 403: Subtask write_to_mysql
[2023-03-22T07:48:25.921+0000] {task_command.py:388} INFO - Running <TaskInstance: sql_dags.write_to_mysql manual__2023-03-22T07:48:23.873072+00:00 [running]> on host aeff5136c067
[2023-03-22T07:48:26.007+0000] {taskinstance.py:1511} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=sql_dags
AIRFLOW_CTX_TASK_ID=write_to_mysql
AIRFLOW_CTX_EXECUTION_DATE=2023-03-22T07:48:23.873072+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-22T07:48:23.873072+00:00
[2023-03-22T07:48:26.669+0000] {taskinstance.py:1775} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/sql_dags.py", line 33, in write_sotck_to_mysql
    write_batch_insert(df=hist, ip="host.docker.internal", user="chris", password="chris")
TypeError: write_batch_insert() missing 2 required positional arguments: 'table' and 'db'
[2023-03-22T07:48:26.680+0000] {taskinstance.py:1326} INFO - Marking task as UP_FOR_RETRY. dag_id=sql_dags, task_id=write_to_mysql, execution_date=20230322T074823, start_date=20230322T074825, end_date=20230322T074826
[2023-03-22T07:48:26.693+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 403 for task write_to_mysql (write_batch_insert() missing 2 required positional arguments: 'table' and 'db'; 1096)
[2023-03-22T07:48:26.750+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-03-22T07:48:27.002+0000] {taskinstance.py:2585} INFO - 0 downstream tasks scheduled from follow-on schedule check
